### ISSUE TITLE
Windows backup automation

### ISSUE THREAD

**Issue by whatageareyouin** [rwoodpecker/KoboBackup#13]
Backup automation is supported on Linux. Let's add support for Windows.

**Comment by whatageareyouin** [comment]
@rwoodpecker What do you think about this feature bossman?

**Comment by rwoodpecker** [comment]
@whatageareyouin I think we should only keep it at basic windows support. Due to philosophical differences (see commentary by Richard Stallman: https://stallman.org/microsoft.html) I do not posses a windows development environment and this will not be implemented unless someone else opens a PR.....

Closing.
